name: Code Validation
on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
      - feature/*
  workflow_dispatch:

jobs: 
  todo:
    runs-on: ubuntu-latest
    # TODO